title: Thoughts
description: A personal blog on technology

url: http://ltcperera.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ltcperera
   twitter: ltcperera
   facebook: ltcperera
   email: ltcperera@gmail.com

google_analytics: "UA-97013803-1"
